### PR TITLE
Pull reorg and extra layers from jrconways3

### PR DESCRIPTION
**Pull request by makrohn**
Makes more sense, some added content, some fixed content.

### CODE REVIEW

**Comment by jrconway3** [comment]
I didn't expect this to actually get merged, but its nice that it did. Sorry for redoing the folder structure; I was just trying to make it easier for me to find things. I've got another set of updates coming soon as I've made some cape sprites and have been working on additional sprites as well.

On another note, I'm going to try and organize my commits better, committing only related items. My next commit, for example, is going to be a whole series of commits related to the cape sprites I made.

**Comment by makrohn** [comment]
Well, it's good work that it needed, and I'm out of the character-design phase right now, so I haven't contributed any updates to it.  I don't mind the folder re-org either; I only work in the XCF, and the .jpgs were put in for tracking changes better with GitHub and for some folks who don't have GIMP 2.8.  

Any future PRs, I'd recommend just organizing commits better to keep track of history, and double-check the AUTHORS.txt file to make sure your contributions are credited!  Also change the name in there if you'd prefer something other than your GitHub handle.

**Comment by jrconway3** [comment]
Thanks. Yeah, I'll be doing a ton of updates as I'm trying to make my own game. The next update may be a little bit though because I have some freelance work to finish up this week before I can continue, but otherwise I'll be trying to actively work on designing all my characters as close as I can get to them, and I'll provide any recolors I make as well as any new sprites I make, plus I'll be fixing up existing entries.

I had noticed I didn't organize my commits very well so I had already planned to clean that up. That's also why I didn't post my cape sprites yet; I was trying to create as many variants as I could before uploading them all at once. I'll check the AUTHORS.txt as well. Thanks for the tips.

**Comment by Gaurav0** [comment]
David,

I'd like to update the online generator. Could you post a list of what moved where?

Gaurav

On Wednesday, October 16, 2013 10:35 AM, David Conway Jr. notifications@github.com wrote:

Thanks. Yeah, I'll be doing a ton of updates as I'm trying to make my own game. The next update may be a little bit though because I have some freelance work to finish up this week before I can continue, but otherwise I'll be trying to actively work on designing all my characters as close as I can get to them, and I'll provide any recolors I make as well as any new sprites I make, plus I'll be fixing up existing entries.
I had noticed I didn't organize my commits very well so I had already planned to clean that up. That's also why I didn't post my cape sprites yet; I was trying to create as many variants as I could before uploading them all at once. I'll check the AUTHORS.txt as well. Thanks for the tips.

**Comment by jrconway3** [comment]
I'm trying to avoid using my real name except on my personal blog site and online profiles I'd share with my clients. I might use it here, though, it all depends.

For the most part I didn't change things around much. Mostly I organized items better in subfolders. That's the main thing I was doing. In some cases I added new subfolders for male/female or I created subfolders for specific types of items. I'm reviewing everything right now and will get back to you on that.

Sorry for the delayed response; having problems with a contract job I'm working on so I haven't had a chance to do sprites this week. Still not done yet (probably not until next week), but I'm going to go through and get you the info now and also commit my cape sprites.

**Comment by jrconway3** [comment]
Reorganization:

I'll denote each section using the root folder is is from. A "/" at the beginning will denote that it is starting at the root. So, for example, the first section below is "/head." This refers to the root directory "head". I listed off each file and showed where I'm moving the file to.

"/head/caps/" indicates that I moved the file from "/head" to the subdirectory of "head", "caps." I just wanted to add this brief description at the beginning to clarify what I meant in case you weren't quite sure what I was getting at.

If I add a filename at the end of the directory listing, that means I also renamed the file. I only do this if I don't think the original filename was clear enough, or I decided to add a color to it because I may create new color alterations in the future.

/head 1)
leather_cap_female.png TO /head/caps/
leather_cap_male.png TO /head/caps/
chain_hood_female.png TO /head/hoods/
chain_hood_male.png TO /head/hoods/
cloth_hood_female.png TO /head/hoods/
cloth_hood_male.png TO /head/hoods/
bandana_male_wconly.png TO /head/bands/
golden_helm_female.png TO /head/helms/
golden_helm_male.png TO /head/helms/
metal_helm_female.png TO /head/helms/
metal_helm_male.png TO /head/helms/
chainhat_female.png TO /head/helms/
chainhat_male.png TO /head/helms/

Notes:
1) Once /head/tiaras_female_no_th_or_sh is fully added I'll rename it "head/tiaras." I'll be doing this as well since I do have characters I'll need tiaras for.

/belt 1)
black_female_no_th-sh.png TO /belt/cloth/female 2)
bronze_female_no_th-sh.png TO /belt/metal/female 3)
brown_female_no_th-sh.png TO /belt/cloth/female 2)
gold_female_no_th-sh.png TO /belt/metal/female 3)
iron_female_no_th-sh.png TO /belt/metal/female 3)
leather_female.png TO /belt/leather/female
leather_male.png TO /belt/leather/male
rope_female.png TO /belt/cloth/female/white_cloth_female.png 4)
rope_male.png TO /belt/cloth/male/white_cloth_male.png 4)
silver_female_no_th-sh.png TO /belt/metal/female 3)

Notes:
1) For belts, I messed up the names here. I keep mixing up the term "sash" for some reason, I looked it up and its nothing like I thought it was. I'm now organizing the belts by material. The folder structure that is currently in the system says "sash" and "belt," but that doesn't work quite right.
2) The black and brown belts appear the same as the bronze, iron, gold, etc., but the latter seem to signify metal belts, so I put the black and brown belts in with cloth belts.
3) I didn't think it was possible to have metal belts, but these seem to imply they are metal so I moved them to the folder "metal."
4) These were called rope, but they didn't particularly look like ropes, so I just called them "cloth" instead. I also added "white" to the beginning because I'll be recoloring them, too.

The "buckles" folder I have not touched at all.

/feet 1)
black_shoes_female.png TO /feet/shoes/female
black_shoes_male.png TO /feet/shoes/male
brown_shoes_female.png TO /feet/shoes/female
brown_shoes_male.png TO /feet/shoes/male
golden_boots_female.png TO /feet/armor/female 2)
golden_boots_male.png TO /feet/armor/male 2)
metal_boots_female.png TO /feet/armor/female 2)
metal_boots_male.png TO /feet/armor/male 2)

Notes:
1) I didn't move "ghillies" yet because I don't know exactly what that means, so I just left it for now.
2) I think I named the metal boots "armor" instead of "boots" or "metal boots" because I didn't want to include two words, and boots will probably be used later for regular every day boots instead of metal boots. And "feet/armor" makes more sense than "feet/metal boots." We can rename it "armour" if anyone else thinks it'd be better that way.

/hands 1)
bracelet.png TO /hands/bracelets/female
golden_gloves_female.png TO /hands/gloves/female
golden_gloves_male.png TO /hands/gloves/male
metal_gloves_female.png TO /hands/gloves/female
metal_gloves_male.png TO /hands/gloves/male

1) I also created a "/hands/bracers" folder and created my own set of bracers to put in there. I later found that there were bracers somewhere else which I moved here as well.

/legs
golden_greaves_female.png TO /legs/armor/female
golden_greaves_male.png TO /legs/armor/male
green_pants_female.png TO /legs/pants/female/teal_pants_female.png 1) 2)
green_pants_male.png TO /legs/pants/male/teal_pants_male.png 1)
metal_pants_female.png TO /legs/armor/female/
metal_pants_male.png TO /legs/armor/male/
red_pants_male.png TO /legs/pants/female/magenta_pants.male.png 1)
robe_skirt_female_incomplete.png TO /legs/skirt/female 3)
robe_skirt_male.png TO /legs/skirt/male 3)

1) I renamed the green and red pants to teal and magenta, respectively, because they didn't really look much like green/red to me.
2) In addition to renaming the female green pants, I also recolored a magenta variation for females and created a new actual red female set of pants, which I then used to create a red male set of pants.
3) In the actual folder listing I did not include the female and male folders under skirts, but I'm going to do that soon.

/torso
brown_shirt_male.png TO /torso/shirts/longsleeve 1)
dress_w_sash_female.png TO /dress_female
pirate_shirt_female.png TO /torso/shirts/sleeveless/white_pirate_female.png 2)
white_shirt_male.png TO /torso/shirts/longsleeve 1)
wings_no_th-sh.png TO /back/wings 3)

Notes:
1) I created a new "shirts" folder and longsleeve, shortsleeve, and sleeveless. The male shirts were both longsleeve so I put them there, but eventually I'll get longsleeve female shirts as well.
2) The pirate shirt is actually a spaghetti strap, might be better to call it that, but I still left it in the sleeveless folder. I then used the pirate shirt to create a full sleeveless shirt as well.
3) The wings I felt just didn't belong under torso at all. I created a new folder called "back" and put them in there. I'll be putting cape sprites (in front of body) into the "back" folder as well.

I recently came up with the idea of putting the "back" folder into the root directory instead, I think that would make more sense, but I'm not sure about this right now.

/torso/leather
bracers_female.png TO /hands/bracers/female
bracers_male.png TO /hands/bracers/male

/torso/chain
tabard TO /torso 1)

1) I haven't done this yet, but the tabard doesn't really look much like chainmail, and I read up online that tabards are usually actually leather, not chainmail.

There's probably other areas this can be organized as well, but I'm still working over the possibilities. I'm going to try and make a few commits now with the latest updates.

**Comment by Gaurav0** [comment]
Okay, I've updated http://gaurav.munjal.us/Universal-LPC-Spritesheet-Character-Generator Please update your links, koding.com is no longer providing me hosting. Also, please report anything missing or not working correctly.

**Pull request merged**
