### PR TITLE
Even more colours.

### PR DESCRIPTION
**Pull request by caeles0**

### CODE REVIEW

**Comment by makrohn** [comment]
These look great!

**Comment by makrohn** [comment]
@caeles0 Did you create these layers, or was it actually Johannes Sjolund?  I'd like to add proper attribution to the AUTHORS file.

**Comment by caeles0** [comment]
On Fri, Mar 08, 2013 at 06:01:46AM -0800, Matthew Krohn wrote:

> @caeles0 Did you create these layers, or was it actually Johannes Sjolund?  I'd like to add proper attribution to the AUTHORS file.

The layers as an arrangement of frames are neither by me nor by Wulax.
(edit: thrust and shoot are by him, but that was not why I mentioned his name
in the commit)
They are simple recolourings of existing layers. I used the "light" skin
versions and (IIRC) the blue eyes as a basis. In case of the male body, I
also reduced the number of colours to the intended 10 (the layer has 82
colours, assumedly by careless edits).

The colours _to_ which I changed are ripped from
"Johannes_Sjolund__Character animations, clothes, armor, weapons, skeleton enemy, combat dummy/examples/dark_skinned_knight.gif".
(Yes, I took the gif; as mentioned elsewhere I cannot open xcfs of gimp > 2.6)
I liked that one better than the dark layers which already were in the
universal sheet. Hence the edit.

About previous edits:

For the hair I used "base_assets/hairfemale.png", because that one has 6
colours per frame, while the existing layers had only 5 colours (the highlight
had got merged with the brightest other colour). I copied these frames all
over the new layers, taking the existing layers as a reference for the correct
positions. Then I subtracted pixels which were transparent in the existing
layers (because some arm obscures the hair). The result is the dark-blonde
layer. For the other layers I recoloured the dark-blonde layer using colours
from "Luke_Mehl__Female\ Mage\ Clothing\ Set/hair/", and later from the hair
layers by Joe White.
For ponytail2, I did not use "base_assets/hairfemale.png", because it's not
there and the existing layers already have 6 colours.

In summary, I consider my contributions of editorial/technical nature.

I see that you try to state exactly one author per layer. I doubt that will
remain feasible. Concerning the layers which I touched, the following would
already be more accurate:

body/female/red_orc_wc_only.png
body/female/orc.png:
Copyright 2012 by Stephen Challener (walk cycle, hurt, slash, spellcast)
Copyright 2012 by Johannes Sjölund (thrust, shoot)
Copyright by Marcel van de Steeg (head)
modified 2012,2013 by Matthew Krohn
modified 2013 by Mark Weyer

body/female/dark.png
body/female/light.png
body/female/tanned.png
body/female/tanned2.png:
Copyright 2012 by Stephen Challener (walk cycle, hurt, slash, spellcast)
Copyright 2012 by Johannes Sjölund (thrust, shoot)
modified 2012,2013 by Matthew Krohn
modified 2013 by Mark Weyer

belt/leather_female.png
belt/rope_female.png:
Copyright 2012 by Johannes Sjölund
Copyright 2012 by Matthew Krohn
modified 2013 by Matthew Krohn
modified 2013 by Mark Weyer

belt/black_female_no_th-sh.png
belt/bronze_female_no_th-sh.png
belt/brown_female_no_th-sh.png
belt/gold_female_no_th-sh.png
belt/iron_female_no_th-sh.png
belt/silver_female_no_th-sh.png
torso/robes_female_no_th-sh/black.png
torso/robes_female_no_th-sh/blue.png
torso/robes_female_no_th-sh/brown.png
torso/robes_female_no_th-sh/dark brown.png
torso/robes_female_no_th-sh/dark gray.png
torso/robes_female_no_th-sh/forest green.png
torso/robes_female_no_th-sh/light gray.png
torso/robes_female_no_th-sh/purple.png
torso/robes_female_no_th-sh/red.png
torso/robes_female_no_th-sh/white.png:
Copyright 2012 by Luke Mehl
modified 2012,2013 by Matthew Krohn
modified 2013 by Mark Weyer

hair/female/_/dark-blonde.png
except hair/female/princess/_ and hair/female/ponytail2/*:
Copyright 2012 by Manuel Riecke
modified 2012,2013 by Matthew Krohn
modified 2013 by Mark Weyer

hair/female/_/black.png
hair/female/_/brown.png
hair/female/_/gray.png
hair/female/_/light-blonde.png
hair/female/_/white.png
except hair/female/princess/_ and hair/female/ponytail2/*:
Copyright 2012 by Manuel Riecke (shape)
Copyright 2012 by Manuel Riecke or Luke Mehl (colour)
modified 2012,2013 by Matthew Krohn
modified 2013 by Mark Weyer

hair/female/ponytail2/black.png
hair/female/ponytail2/brown.png
hair/female/ponytail2/gray.png
hair/female/ponytail2/light-blonde.png
hair/female/ponytail2/white.png:
Copyright 2013 by Joe White (shape)
Copyright 2012 by Manuel Riecke or Luke Mehl (colour)
modified 2013 by Matthew Krohn
modified 2013 by Mark Weyer

hair/female/_/blonde.png
hair/female/_/brunette.png
hair/female/_/raven.png
hair/female/_/white-blonde.png
except hair/female/ponytail2/\* and hair/female/princess/*
Copyright 2012 by Manuel Riecke (shape)
Copyright 2013 by Joe White (colour)
modified 2012,2013 by Matthew Krohn
modified 2013 by Mark Weyer

body/female/dark2.png
body/female/eyes/gray.png
body/male/dark2.png
body/male/eyes/gray.png:
Copyright 2012 by Stephen Challener (walk cycle, hurt, slash, spellcast)
Copyright 2012 by Johannes Sjölund (thrust, shoot, colour)
modified 2012,2013 by Matthew Krohn
modified 2013 by Mark Weyer

**Comment by makrohn** [comment]
That makes my eyes bleed a little.  I wonder if there's a more elegant solution.

**Comment by caeles0** [comment]
> That makes my eyes bleed a little.  I wonder if there's a more elegant solution.

Let me know when you find one. I don't like it very much either, but it's what
I use myself for lack of anything better.

**Pull request merged**
