### PR TITLE
More Reorganization and New Sprite Additions

### PR DESCRIPTION
**Pull request by jrconway3**
I made a bunch of changes last Friday (not yesterday), then today I just added a couple of things.

I rename the folders in belts from before because I looked up the correct term for sashes and I used it incorrectly. No matter what waist belt material is made of they're still belts, so I sorted them by material instead.

One thing I've been doing is adding male/female directories to a variety of folders just to make things a bit easier. I did this some more, adding male/female directories to legs/skirt, head/helms, head/hats, head/caps, head/bands, torso/shirts/longsleeve, torso/shirts/shortsleeve, and torso/shirts/sleeveless.

The only other reorganization I did is I moved the "Quiver" from behind_back to behind_back/equipment and Wings from torso/back to torso/back/wings.

Everything else I added is new. I fixed some animations for Elven Ears that were slightly off and added new skintones. I added new recolors in some areas just to fill them out and keep things consistent. Other recolors were added so I could use them for my sprites. I fixed all the female hairstyles so they had the hurt animations, too.

The biggest update is the addition of capes. I think it could still use some work, but I like the base design. I really would like feedback on the capes so I can know how to accurately adjust the animations to look better if needed. I also added tunic sprites, which is modded from my sleeveless shirt sprites. I will start getting into adding longer sleeve shirts for female sprites soon.

Today I also fixed the link in README.md to the online version and also updated my own entry in AUTHORS.txt.

I also finished tattered cape sprites for now; might still touch it up later. What I have just done here is used a cutout for all the animations and adjust it slightly for each one. Brown cape sprites were also added using the palette from the hood sprites.

### CODE REVIEW

**Comment by Gaurav0** [comment]
Hi David,

I've updated the online generator today. Please check it and bring up any issues

Gaurav

**Comment by jrconway3** [comment]
I don't think these changes have been merged yet. I can take a look at it, though.

**Comment by jrconway3** [comment]
Ok, I reviewed it. There are several things I noticed.

1.) The Cloth and Leather bracers are identical. I created a separate set of Cloth Bracers which look a little different from the old bracers, I differentiated them by calling the old one "leather" and mine "cloth." I also added two recolors of Cloth Bracers, too, one is white, and one is white with the lightest color replaced with a darker gray to make it look closer to a bandage wrap (I may tweak it later, but its hard to see such small sprites anyway).

2.) None of the Cape Clips/Ties show up. These are located in accessories/neck.

3.) None of the parts of the cape behind the body show up. These are located separately from the main cape in behind_body/cape.

Now, a couple of ideas I have to make it cleaner:

1.) For recolors, maybe it would be best to have it appear like hair colors? In other words, make it open up further down and list the recolors off that way.

2.) For the hair, I think each hairstyle should probably have an arrow or something so users know that they can click on it to get more results. Its just a usability issue.

3.) I think it might be a good idea to add more hair colors. But its up to you. I've been trying to fill out all the hairstyles so that they are consistent; every hairstyle has all the same hair colors. I've done this for female sprites and will do it for male later.

Sometimes I also find that the existing hair colors aren't close enough to the characters I'm trying to make, so I go in and create new ones. That's why I created ruby-red and white-cyan. Once I created these hair colors I then promptly went in and added the same hair colors to all female sprites as well.

Its up to you if you want to include all of them, but some users might like a larger variety. I'm creating them all regardless because at certain points my characters might alter their hairstyle for specific reasons so I might as well just add the recolors for all hairstyles, and since I'm making them I might as well upload them as well.

Right now I'm going through another character of mine and touching up some of the existing hairstyles. For example, updating those hurt animations so it actually looks like the top of the head. Ponytail 2 is currently the only one to have this. I'm updating at least Loose, my two Curly Hair styles, and Swoop because my characters so far are using these ones.

After I update these hairstyles I'll start doing some male sprites finally.

**Comment by jrconway3** [comment]
Gaurav, I just noticed that you had a repo for the online character generator as well. I went and forked it and I'll see about starting to make some updates myself instead of waiting for you to do them.

I also went through and fixed some more of the accessories last night. I fixed the nose and ears sprites. I think I'll move onto glasses today. And yes I will be using some of these later, so I figured that I might as well fix the positioning now.

EDIT: Nevermind, I see that you did already. :P Well I'll start following it so I can keep an eye on updates.

**Comment by Gaurav0** [comment]
Thanks, I appreciate the help. I have a lot of catching up to do with the hair styles / colors.

**Comment by jrconway3** [comment]
Yeah, I just noticed that the hair colors aren't up yet. I'm working on adding all the female hair colors in now and I'll commit it to the fork I created. Later I'll fill in all the male hair colors, but I'm not going to do that until I finish the hurt animations for those.

For the female hairstyles I've only done three of the fixed hurt animations so far and only one is committed (Loose). I haven't even started on the male ones yet. But since I do have the recolors up I'll fill them in and later update the source files to have the fixed hurt animations. (Though a couple of them are already done so I don't have to update those ones.)

Another weird thing, I didn't realize that committing new things would automatically add them to the same pull request. I'm still getting used to Github as I haven't been using it as actively as I'd like.

**Comment by Gaurav0** [comment]
Thanks for merging, Matthew!

**Comment by makrohn** [comment]
"Another weird thing, I didn't realize that committing new things would automatically add them to the same pull request. I'm still getting used to Github as I haven't been using it as actively as I'd like."

What you really want to do is use branches, @jrconway3 

```
git branch darkelves
git checkout darkelves
```

Do your work

```
git push origin darkelves
```

And then do the pull request off of that.  Once the pull request is merged, github.com will actually show you a button to safely delete the merged branch.  I'll try to keep up with them better, too.

**Comment by jrconway3** [comment]
Yeah, that sounds good. I've been using branches with a client I started working with on Github; they do everything on Github and asked me to use branches instead of forks. In this case I probably will use both; I'll merge my branches into my own master, but selectively choose which branches to do pull requests on.

For example, pull requests to README.md aren't necessary; when I do make changes that should be in the main one I can create a separate branch for it.

It'd be easier to keep things organized when I do a batch of updates and make that one branch, or keep a batch of related updates together.

And thanks for merging all this, too. I'll try and go with branches from now on for better organization (although as noted elsewhere, I won't be updating much for a while yet, but I will get back to doing updates eventually).

**Pull request merged**
